const cfg=window.TLAZOTLI_SUPABASE||{};const db=window.supabase.createClient(cfg.url,cfg.publicKey);let cache={products:[],orders:[],customers:[],subscribers:[],coupons:[],recommendations:[]};
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function init(){const{data}=await db.auth.getSession();setSession(data.session);db.auth.onAuthStateChange((_e,s)=>setSession(s));}
function setSession(s){$('#login').hidden=!!s;$('#app').hidden=!s;if(s)loadAll();}
$('#loginBtn').onclick=async()=>{const{error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});$('#loginMsg').textContent=error?error.message:''};$('#logoutBtn').onclick=()=>db.auth.signOut();
document.querySelectorAll('.navbtn[data-module]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.module').forEach(m=>m.classList.remove('active'));$('#'+b.dataset.module).classList.add('active')});
async function safe(table,query='*'){const{data,error}=await db.from(table).select(query);if(error){console.warn(table,error.message);return[]}return data||[]}
async function loadAll(){cache.products=await safe('products');cache.orders=await safe('orders');cache.customers=await safe('customers');cache.subscribers=await safe('subscribers');cache.coupons=await safe('coupons');cache.recommendations=await safe('product_recommendations');renderAll();loadSettings();}
function renderAll(){$('#mProducts').textContent=cache.products.length;$('#mOrders').textContent=cache.orders.length;$('#mCustomers').textContent=cache.customers.length;$('#mSubscribers').textContent=cache.subscribers.length;renderAlerts();renderProducts();renderOrders();renderCustomers();renderSubscribers();renderRewards();renderCoupons();renderRecommendations();}
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`}
function renderAlerts(){const low=cache.products.filter(p=>Number(p.stock||0)<=Number(p.low_stock_threshold||3));const stalled=cache.products.filter(p=>Number(p.stock||0)>5&&!p.featured&&!p.on_sale);$('#alerts').innerHTML=[...low.slice(0,8).map(p=>`<div class="notice">⚠ Inventario bajo: <strong>${esc(p.name)}</strong> (${p.stock||0})</div>`),...stalled.slice(0,5).map(p=>`<div class="notice">📉 Revisa movimiento: <strong>${esc(p.name)}</strong>. Considera destacarlo o crear una oferta.</div>`)].join('')||'<div class="notice">Sin alertas importantes.</div>'}
function renderProducts(){$('#productsTable').innerHTML=table(['Producto','Precio','Stock','Estado'],cache.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.price==null?'Consultar':`$${p.price}`}</td><td>${p.stock||0}</td><td>${p.active?'Visible':'Oculto'}${p.on_sale?' · Oferta':''}</td></tr>`))}
function renderOrders(){$('#ordersTable').innerHTML=table(['Pedido','Cliente','Total','Estado','Fecha'],cache.orders.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).map(o=>`<tr><td>#${o.order_number||''}</td><td>${esc(o.customer_name||'Sin nombre')}</td><td>$${o.total||0}</td><td><select data-order="${o.id}"><option value="pending" ${o.status==='pending'?'selected':''}>Pendiente</option><option value="paid" ${o.status==='paid'?'selected':''}>Pagado</option><option value="delivered" ${o.status==='delivered'?'selected':''}>Entregado</option><option value="cancelled" ${o.status==='cancelled'?'selected':''}>Cancelado</option></select></td><td>${new Date(o.created_at).toLocaleDateString('es-MX')}</td></tr>`));document.querySelectorAll('[data-order]').forEach(s=>s.onchange=async()=>{await db.from('orders').update({status:s.value,updated_at:new Date().toISOString()}).eq('id',s.dataset.order);loadAll()})}
function renderCustomers(){$('#customersTable').innerHTML=table(['Nombre','WhatsApp','Compras','Total'],cache.customers.map(c=>`<tr><td>${esc(c.name||'')}</td><td>${esc(c.whatsapp||c.phone||'')}</td><td>${c.completed_purchases||0}</td><td>$${c.total_spent||0}</td></tr>`))}
function renderSubscribers(){$('#subscribersTable').innerHTML=table(['Nombre','WhatsApp','Correo','Fecha'],cache.subscribers.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.whatsapp)}</td><td>${esc(s.email||'')}</td><td>${new Date(s.created_at).toLocaleDateString('es-MX')}</td></tr>`))}
function renderRewards(){const rows=cache.customers.map(c=>{const n=Number(c.completed_purchases||0);const reward=n>=10?'20%':n>=5?'10%':'—';return `<tr><td>${esc(c.name||'')}</td><td>${n}</td><td>${reward}</td><td>${n>=10?'Oro':n>=5?'Plata':'Bronce'}</td></tr>`});$('#rewardsTable').innerHTML=table(['Cliente','Compras','Beneficio','Nivel'],rows)}
$('#saveCoupon').onclick=async()=>{const payload={code:$('#couponCode').value.trim().toUpperCase(),discount_type:$('#couponType').value,discount_value:Number($('#couponValue').value),minimum_purchase:Number($('#couponMin').value||0),active:true};if(!payload.code||!payload.discount_value)return alert('Completa código y descuento');const{error}=await db.from('coupons').insert(payload);if(error)return alert(error.message);loadAll()};
function renderCoupons(){$('#couponsTable').innerHTML=table(['Código','Descuento','Mínimo','Estado'],cache.coupons.map(c=>`<tr><td>${esc(c.code)}</td><td>${c.discount_type==='percent'?c.discount_value+'%':'$'+c.discount_value}</td><td>$${c.minimum_purchase||0}</td><td>${c.active?'Activo':'Inactivo'}</td></tr>`))}
function renderRecommendations(){const generated=[];cache.products.forEach(p=>{if(Number(p.stock||0)>8&&!p.on_sale&&!p.featured)generated.push({title:'Producto con inventario alto',details:p.name,action:'Considera oferta de 10% o destacarlo.'});if(Number(p.stock||0)<=Number(p.low_stock_threshold||3))generated.push({title:'Inventario bajo',details:p.name,action:'Revisar resurtido.'})});const stored=cache.recommendations.map(r=>({title:r.title,details:r.details,action:r.suggested_action}));$('#recommendationsList').innerHTML=[...stored,...generated].slice(0,30).map(r=>`<div class="notice"><strong>${esc(r.title)}</strong><br>${esc(r.details||'')}<br><small>${esc(r.action||'')}</small></div>`).join('')||'<div class="notice">Todavía no hay recomendaciones.</div>'}
async function loadSettings(){const{data}=await db.from('store_settings').select('*').eq('id',1).maybeSingle();if(!data)return;$('#sWhatsapp').value=data.whatsapp||'';$('#sInstagram').value=data.instagram||'';$('#sTiktok').value=data.tiktok||'';$('#sBank').value=data.bank_name||'';$('#sHolder').value=data.bank_holder||'';$('#sAccount').value=data.bank_account||'';$('#sMessage').value=data.purchase_message||data.payment_note||''}
$('#saveSettings').onclick=async()=>{const payload={whatsapp:$('#sWhatsapp').value.trim(),instagram:$('#sInstagram').value.trim(),tiktok:$('#sTiktok').value.trim(),bank_name:$('#sBank').value.trim(),bank_holder:$('#sHolder').value.trim(),bank_account:$('#sAccount').value.trim(),purchase_message:$('#sMessage').value.trim(),updated_at:new Date().toISOString()};const{error}=await db.from('store_settings').update(payload).eq('id',1);alert(error?error.message:'Configuración guardada')};
$('#exportProducts').onclick=()=>{const cols=['code','name','brand','price','category','stock','active'];const csv=[cols.join(','),...cache.products.map(p=>cols.map(c=>`"${String(p[c]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='productos-tlazotli.csv';a.click()};
init();

(function addAdminSwitcher(){
  const style=document.createElement('style');
  style.textContent='.admin-switcher{position:fixed;right:18px;bottom:18px;z-index:9999;display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end;max-width:94vw}.admin-switcher a{display:inline-flex;align-items:center;gap:6px;text-decoration:none;border-radius:999px;padding:11px 15px;font-weight:800;box-shadow:0 8px 24px #0002;background:#fff;color:#222;border:1px solid #eadce1}.admin-switcher a.current{background:var(--olive);color:#fff}.admin-switcher a:hover{transform:translateY(-1px)}';
  document.head.appendChild(style);
  const nav=document.createElement('nav');
  nav.className='admin-switcher';
  nav.setAttribute('aria-label','Cambiar sección administrativa');
  nav.innerHTML='<a href="admin.html">🛠 Editor</a><a class="current" href="admin-center.html">📊 Centro administrativo</a><a href="index.html" target="_blank" rel="noopener">🛍 Ver tienda</a>';
  document.body.appendChild(nav);
})();