const cfg=window.TLAZOTLI_SUPABASE||{};const configured=cfg.url&&cfg.publicKey&&window.supabase;const $=s=>document.querySelector(s);let client=null,products=[],editing=null;
function msg(el,text,error=false){el.textContent=text;el.classList.remove('hidden');el.style.background=error?'#fde8ee':'var(--blush)'}
if(!configured){$('#config-warning').classList.remove('hidden');$('#login-section').classList.add('hidden')}else{client=window.supabase.createClient(cfg.url,cfg.publicKey);init()}
async function init(){const{data}=await client.auth.getSession();session(data.session);client.auth.onAuthStateChange((_,s)=>session(s))}
function session(s){$('#login-section').classList.toggle('hidden',!!s);$('#admin-section').classList.toggle('hidden',!s);if(s)load()}
$('#login-button').addEventListener('click',async()=>{const{error}=await client.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});if(error)msg($('#login-message'),error.message,true)});
$('#logout-button').addEventListener('click',()=>client.auth.signOut());$('#save-product').addEventListener('click',save);$('#cancel-edit').addEventListener('click',reset);$('#admin-search').addEventListener('input',()=>render());
$('#new-product-shortcut').addEventListener('click',()=>{reset();window.scrollTo({top:250,behavior:'smooth'})});$('#show-out-shortcut').addEventListener('click',()=>render('out'));$('#show-sale-shortcut').addEventListener('click',()=>render('sale'));
async function upload(file,name){if(!file)return null;const ext=file.name.split('.').pop().toLowerCase();const path=`${Date.now()}-${name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-')}.${ext}`;const{error}=await client.storage.from('product-images').upload(path,file);if(error)throw error;return client.storage.from('product-images').getPublicUrl(path).data.publicUrl}
async function save(){const name=$('#product-name').value.trim(),priceText=$('#product-price').value.trim(),price=priceText===''?null:Number(priceText),stock=Number($('#product-stock').value||0),low=Number($('#product-low-stock').value||0),saleText=$('#product-sale-price').value.trim(),sale=saleText===''?null:Number(saleText),onSale=$('#product-on-sale').checked,file=$('#product-image').files[0];if(!name||stock<0||low<0||Number.isNaN(stock)||Number.isNaN(low)||price!==null&&(!Number.isFinite(price)||price<0))return msg($('#save-message'),'Revisa nombre, precio e inventario.',true);if(onSale&&(sale===null||sale<0||price===null||sale>=price))return msg($('#save-message'),'La oferta debe ser menor al precio normal.',true);if(!editing&&!file)return msg($('#save-message'),'Selecciona una fotografía.',true);try{let image=editing?.image_url||null;if(file)image=await upload(file,name);const payload={code:$('#product-code').value.trim()||null,name,brand:$('#product-brand').value.trim()||null,price,category:$('#product-category').value,description:$('#product-description').value.trim()||null,image_url:image,active:$('#product-active').checked,stock,low_stock_threshold:low,on_sale:onSale,sale_price:onSale?sale:null,featured:$('#product-featured').checked,is_new:$('#product-new').checked,best_seller:$('#product-best-seller').checked,updated_at:new Date().toISOString()};const q=editing?client.from('products').update(payload).eq('id',editing.id):client.from('products').insert(payload);const{error}=await q;if(error)throw error;msg($('#save-message'),editing?'Producto actualizado.':'Producto publicado.');reset(false);await load()}catch(e){msg($('#save-message'),e.message||'No se pudo guardar.',true)}}
function edit(id){const p=products.find(x=>x.id===id);if(!p)return;editing=p;$('#form-title').textContent=`Editar: ${p.name}`;$('#save-product').textContent='Guardar cambios';$('#cancel-edit').classList.remove('hidden');$('#product-code').value=p.code||'';$('#product-name').value=p.name||'';$('#product-brand').value=p.brand||'';$('#product-price').value=p.price??'';$('#product-stock').value=p.stock??0;$('#product-low-stock').value=p.low_stock_threshold??3;$('#product-category').value=p.category||'Otros';$('#product-description').value=p.description||'';$('#product-active').checked=!!p.active;$('#product-on-sale').checked=!!p.on_sale;$('#product-sale-price').value=p.sale_price??'';$('#product-featured').checked=!!p.featured;$('#product-new').checked=!!p.is_new;$('#product-best-seller').checked=!!p.best_seller;window.scrollTo({top:250,behavior:'smooth'})}
function reset(clear=true){editing=null;$('#form-title').textContent='Agregar producto';$('#save-product').textContent='Guardar producto';$('#cancel-edit').classList.add('hidden');['#product-code','#product-name','#product-brand','#product-price','#product-description','#product-image','#product-sale-price'].forEach(s=>$(s).value='');$('#product-stock').value=0;$('#product-low-stock').value=3;$('#product-active').checked=true;$('#product-on-sale').checked=false;$('#product-featured').checked=false;$('#product-new').checked=false;$('#product-best-seller').checked=false;if(clear)$('#save-message').classList.add('hidden')}
async function load(){const c=$('#admin-products');c.innerHTML='<p>Cargando…</p>';const{data,error}=await client.from('products').select('*').order('created_at',{ascending:false});if(error){c.innerHTML=`<p>${esc(error.message)}</p>`;return}products=data||[];summary();render()}
function summary(){$('#summary-total').textContent=products.length;$('#summary-active').textContent=products.filter(p=>p.active).length;$('#summary-out').textContent=products.filter(p=>Number(p.stock||0)===0).length;$('#summary-low').textContent=products.filter(p=>Number(p.stock||0)>0&&Number(p.stock||0)<=Number(p.low_stock_threshold??3)).length;$('#summary-sale').textContent=products.filter(p=>p.on_sale).length}
function render(filter=''){const term=$('#admin-search').value.trim().toLowerCase();let data=products.filter(p=>`${p.code||''} ${p.name} ${p.brand||''} ${p.category}`.toLowerCase().includes(term));if(filter==='out')data=products.filter(p=>Number(p.stock||0)===0);if(filter==='sale')data=products.filter(p=>p.on_sale);$('#admin-products').innerHTML=data.length?data.map(p=>{const stock=Number(p.stock||0),low=Number(p.low_stock_threshold??3),price=p.on_sale&&p.sale_price!=null?`<strong>$${p.sale_price}</strong> <s>$${p.price}</s>`:`<strong>${p.price==null?'Consultar precio':'$'+p.price}</strong>`;return `<article class="product-admin-row"><img src="${p.image_url||''}" alt="${esc(p.name)}"><div><strong>${esc(p.name)}</strong><div class="brand">${esc(p.code||'Sin SKU')} · ${esc(p.category)} · ${price}</div><div><span class="status-chip">${p.active?'Visible':'Oculto'}</span><span class="status-chip">Inventario: ${stock}</span>${stock===0?'<span class="status-chip">Agotado</span>':''}${stock>0&&stock<=low?'<span class="status-chip">Pocas piezas</span>':''}${p.on_sale?'<span class="status-chip offer-chip">Oferta</span>':''}${p.featured?'<span class="status-chip offer-chip">Destacado</span>':''}${p.is_new?'<span class="status-chip offer-chip">Nuevo</span>':''}${p.best_seller?'<span class="status-chip offer-chip">Más vendido</span>':''}</div></div><div class="row-actions"><button class="small-btn edit-btn" data-edit="${p.id}">Editar</button><button class="small-btn stock-btn" data-delta="-1" data-id="${p.id}">− Inventario</button><button class="small-btn stock-btn" data-delta="1" data-id="${p.id}">+ Inventario</button><button class="small-btn offer-btn" data-offer="${p.id}">${p.on_sale?'Quitar oferta':'Poner oferta'}</button><button class="small-btn copy-btn" data-copy="${p.id}">Duplicar</button><button class="small-btn toggle-btn" data-toggle="${p.id}">${p.active?'Ocultar':'Mostrar'}</button><button class="small-btn danger" data-delete="${p.id}">Eliminar</button></div></article>`}).join(''):'<p>No se encontraron productos.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>edit(b.dataset.edit)));document.querySelectorAll('[data-delta]').forEach(b=>b.addEventListener('click',()=>stock(b.dataset.id,Number(b.dataset.delta))));document.querySelectorAll('[data-offer]').forEach(b=>b.addEventListener('click',()=>offer(b.dataset.offer)));document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>copy(b.dataset.copy)));document.querySelectorAll('[data-toggle]').forEach(b=>b.addEventListener('click',()=>toggle(b.dataset.toggle)));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>remove(b.dataset.delete)))}
async function stock(id,d){const p=products.find(x=>x.id===id);const{error}=await client.from('products').update({stock:Math.max(0,Number(p.stock||0)+d),updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else load()}
async function offer(id){const p=products.find(x=>x.id===id);if(p.on_sale){const{error}=await client.from('products').update({on_sale:false,sale_price:null}).eq('id',id);if(error)alert(error.message);else load();return}const raw=prompt(`Precio normal: ${p.price??'sin precio'}\nPrecio de oferta:`);if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)||p.price==null||value<0||value>=Number(p.price))return alert('La oferta debe ser menor al precio normal.');const{error}=await client.from('products').update({on_sale:true,sale_price:value}).eq('id',id);if(error)alert(error.message);else load()}
async function copy(id){const p=products.find(x=>x.id===id),payload={code:null,name:`${p.name} (copia)`,brand:p.brand,price:p.price,category:p.category,description:p.description,image_url:p.image_url,active:false,stock:0,low_stock_threshold:p.low_stock_threshold??3,on_sale:false,sale_price:null,featured:false,is_new:false,best_seller:false};const{error}=await client.from('products').insert(payload);if(error)alert(error.message);else load()}
async function toggle(id){const p=products.find(x=>x.id===id);const{error}=await client.from('products').update({active:!p.active}).eq('id',id);if(error)alert(error.message);else load()}
async function remove(id){const p=products.find(x=>x.id===id);if(!p||!confirm(`¿Eliminar “${p.name}”? No se puede deshacer.`))return;const{error}=await client.from('products').delete().eq('id',id);if(error)alert(error.message);else{if(editing?.id===id)reset();load()}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
