const PRODUCTS=[
{id:'TLA-001',name:'Cremas para manos CEO y Paris Meet',brand:'CEO / Paris Meet',category:'Cuidado corporal',price:70,label:'$70 MXN c/u',emoji:'🧴',description:'Cremas para manos en tubos compactos, prácticas para llevar y aplicar durante el día.'},
{id:'TLA-002',name:'Nerds Rainbow',brand:'Nerds',category:'Dulces y snacks',price:75,label:'$75 MXN',emoji:'🍬',description:'Caramelos pequeños y crujientes con sabores frutales variados en una caja práctica.'},
{id:'TLA-003',name:'Sour Patch Kids Original',brand:'Sour Patch Kids',category:'Dulces y snacks',price:75,label:'$75 MXN',emoji:'🍭',description:'Gomitas con mezcla de sabores frutales y el característico contraste ácido-dulce.'},
{id:'TLA-004',name:'Lemonhead',brand:'Lemonhead',category:'Dulces y snacks',price:75,label:'$75 MXN',emoji:'🍋',description:'Caramelos con intenso sabor a limón y perfil cítrico en presentación de caja.'},
{id:'TLA-005',name:'SweeTarts Original',brand:'SweeTarts',category:'Dulces y snacks',price:75,label:'$75 MXN',emoji:'🍬',description:'Caramelos comprimidos con sabores frutales y un toque ácido.'},
{id:'TLA-006',name:'Jabón espumoso Pumpkin Pecan Waffles',brand:'Bath & Body Works',category:'Cuidado corporal',price:80,label:'$80 MXN',emoji:'🧼',description:'Jabón espumoso para manos con dispensador, ideal para baño o tocador.'},
{id:'TLA-007',name:'Lápices de colores, 12 piezas',brand:'Crayola',category:'Papelería',price:80,label:'$80 MXN',emoji:'✏️',description:'Set de doce lápices de colores para dibujo, tareas y actividades creativas.'},
{id:'TLA-008',name:'Vanish Foundation Stick',brand:'Hourglass',category:'Maquillaje',price:80,label:'$80 MXN',emoji:'💄',description:'Base de maquillaje en barra de formato compacto para una aplicación práctica.'},
{id:'TLA-009',name:'Peelez sabor sandía',brand:'Peelez',category:'Dulces y snacks',price:80,label:'$80 MXN',emoji:'🍉',description:'Dulce masticable con presentación inspirada en rebanadas de sandía.'},
{id:'TLA-010',name:'Swedish Fish Tails',brand:'Swedish Fish',category:'Dulces y snacks',price:80,label:'$80 MXN',emoji:'🐟',description:'Gomitas suaves con forma de pez y combinación de dos sabores en cada pieza.'},
{id:'TLA-011',name:'Hi-Chew Fantasy Mix',brand:'Hi-Chew',category:'Dulces y snacks',price:80,label:'$80 MXN',emoji:'🍬',description:'Caramelos masticables de textura suave con una selección de sabores frutales.'},
{id:'TLA-012',name:'Sour Patch Kids Grape',brand:'Sour Patch Kids',category:'Dulces y snacks',price:80,label:'$80 MXN',emoji:'🍇',description:'Gomitas sabor uva con contraste ácido y dulce en bolsa para compartir.'},
{id:'TLA-013',name:'Lucky Charms tamaño familiar',brand:'Lucky Charms',category:'Dulces y snacks',price:80,label:'$80 MXN',emoji:'🥣',description:'Cereal con piezas crujientes y malvaviscos de colores en presentación familiar.'},
{id:'TLA-014',name:'Froot Loops / Cocoa Pebbles en vaso',brand:'Kellogg’s / Post',category:'Dulces y snacks',price:80,label:'$80 MXN c/u',emoji:'🥣',description:'Cereales en presentación individual de vaso, prácticos para una porción rápida.'},
{id:'TLA-015',name:'Marcadores Fine Line, 10 colores',brand:'Crayola',category:'Papelería',price:90,label:'$90 MXN',emoji:'🖍️',description:'Marcadores de punta fina para escritura, dibujo y actividades escolares.'},
{id:'TLA-016',name:'Sour Punch Bites Banana',brand:'Sour Punch',category:'Dulces y snacks',price:90,label:'$90 MXN',emoji:'🍌',description:'Bocados de caramelo suave con cubierta ácida y sabor a plátano.'},
{id:'TLA-017',name:'Blow Pop Minis',brand:'Charms',category:'Dulces y snacks',price:90,label:'$90 MXN',emoji:'🍭',description:'Mini paletas de sabores surtidos, prácticas para compartir o regalar.'},
{id:'TLA-018',name:'Laffy Taffy surtidos',brand:'Laffy Taffy',category:'Dulces y snacks',price:90,label:'$90 MXN',emoji:'🍬',description:'Caramelos masticables en distintos sabores frutales y empaque individual.'},
{id:'TLA-019',name:'Skittles Gummies',brand:'Skittles',category:'Dulces y snacks',price:90,label:'$90 MXN',emoji:'🌈',description:'Gomitas suaves inspiradas en los sabores frutales de Skittles.'},
{id:'TLA-020',name:'Swedish Fish Mini Tropical',brand:'Swedish Fish',category:'Dulces y snacks',price:90,label:'$90 MXN',emoji:'🐟',description:'Gomitas pequeñas con forma de pez y mezcla de sabores tropicales.'},
{id:'TLA-021',name:'Smarties Original',brand:'Smarties',category:'Dulces y snacks',price:90,label:'$90 MXN',emoji:'🍬',description:'Caramelos comprimidos de sabores frutales en presentación clásica.'},
{id:'TLA-022',name:'Goobers',brand:'Goobers',category:'Dulces y snacks',price:90,label:'$90 MXN',emoji:'🥜',description:'Cacahuates cubiertos de chocolate en caja cómoda para disfrutar como snack.'},
{id:'TLA-023',name:'Krabby Patties Watermelon',brand:'Krabby Patties',category:'Dulces y snacks',price:90,label:'$90 MXN',emoji:'🍔',description:'Gomitas con forma de mini hamburguesa y sabor sandía.'},
{id:'TLA-024',name:'Nerds Gummy Clusters Rainbow',brand:'Nerds',category:'Dulces y snacks',price:90,label:'$90 MXN',emoji:'🍬',description:'Centros suaves de gomita cubiertos con pequeños caramelos crujientes.'},
{id:'TLA-025',name:'Mascarillas Madagascar Centella',brand:'Madagascar Centella',category:'Skincare',price:100,label:'$100 MXN c/u',emoji:'🧖‍♀️',description:'Mascarillas faciales individuales para complementar una rutina de cuidado personal.'},
{id:'TLA-026',name:'Mike and Ike Mega Mix',brand:'Mike and Ike',category:'Dulces y snacks',price:120,label:'$120 MXN',emoji:'🍬',description:'Caramelos masticables con amplia mezcla de sabores frutales en caja.'},
{id:'TLA-027',name:'Hot Tamales Tropical Heat',brand:'Hot Tamales',category:'Dulces y snacks',price:120,label:'$120 MXN',emoji:'🌶️',description:'Caramelos masticables con mezcla tropical y perfil de sabor intenso.'},
{id:'TLA-028',name:'Tarte Maneater Mini',brand:'Tarte',category:'Maquillaje',price:170,label:'$170 MXN',emoji:'👁️',description:'Máscara de pestañas en formato mini, práctica para llevar y usar en retoques.'},
{id:'TLA-029',name:'Organizador para cosméticos y accesorios',brand:'',category:'Accesorios',price:200,label:'$200 MXN',emoji:'🗄️',description:'Organizador con compartimentos para maquillaje, brochas y accesorios pequeños.'},
{id:'TLA-030',name:'Patrick Ta Double-Take Blush Duo',brand:'Patrick Ta',category:'Maquillaje',price:555,label:'$555 MXN',emoji:'🩷',description:'Dúo de rubor con dos presentaciones complementarias para añadir color y dimensión.'},
{id:'TLA-031',name:'Dior Backstage Airflash Mist',brand:'Dior',category:'Maquillaje',price:920,label:'$920 MXN',emoji:'✨',description:'Bruma para complementar y refrescar el acabado del maquillaje.'},
{id:'TLA-032',name:'Trolli Sour Brite Crawlers Very Berry',brand:'Trolli',category:'Dulces y snacks',price:null,label:'Consultar precio',emoji:'🐛',description:'Gomitas ácidas en forma de gusano con mezcla de sabores de frutos rojos.'},
{id:'TLA-033',name:'Mamba Fruit Chews',brand:'Mamba',category:'Dulces y snacks',price:null,label:'Consultar precio',emoji:'🍬',description:'Caramelos masticables de sabores frutales en piezas individuales.'},
{id:'TLA-034',name:'Sour Punch Bites Tropical Blends',brand:'Sour Punch',category:'Dulces y snacks',price:null,label:'Consultar precio',emoji:'🍍',description:'Bocados suaves con cubierta ácida y combinación de sabores tropicales.'}
];

const $=s=>document.querySelector(s);const grid=$('#product-grid'),search=$('#search'),category=$('#category'),sort=$('#sort'),count=$('#result-count'),cartPanel=$('#cart-panel'),overlay=$('#overlay');let cart={};
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
function initCategories(){[...new Set(PRODUCTS.map(p=>p.category))].sort().forEach(c=>category.insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`))}
function productCard(p){return `<article class="product-card"><div class="product-visual"><span class="product-code">${p.id}</span><span class="product-emoji">${p.emoji}</span></div><div class="product-body"><span class="product-category">${p.category}</span><h3 class="product-title">${p.name}</h3>${p.brand?`<div class="brand">Marca: ${p.brand}</div>`:''}<p class="description">${p.description}</p><div class="card-bottom"><span class="price">${p.label}</span><button class="add-button" data-add="${p.id}">Agregar</button></div></div></article>`}
function render(){let items=PRODUCTS.filter(p=>(category.value==='all'||p.category===category.value)&&(`${p.name} ${p.brand} ${p.category} ${p.description}`.toLowerCase().includes(search.value.trim().toLowerCase())));if(sort.value==='price-asc')items.sort((a,b)=>(a.price??1e9)-(b.price??1e9));if(sort.value==='price-desc')items.sort((a,b)=>(b.price??-1)-(a.price??-1));if(sort.value==='name')items.sort((a,b)=>a.name.localeCompare(b.name));grid.innerHTML=items.map(productCard).join('');count.textContent=`${items.length} productos`;document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>add(b.dataset.add)))}
function add(id){cart[id]=(cart[id]||0)+1;updateCart();toast('Producto agregado')}
function change(id,delta){cart[id]=(cart[id]||0)+delta;if(cart[id]<=0)delete cart[id];updateCart()}
function updateCart(){const entries=Object.entries(cart),units=entries.reduce((s,[,q])=>s+q,0);$('#cart-count').textContent=units;$('#cart-units').textContent=units;let total=0;$('#cart-items').innerHTML=entries.length?entries.map(([id,q])=>{const p=PRODUCTS.find(x=>x.id===id);if(p.price)total+=p.price*q;return `<div class="cart-item"><div><h3>${p.name}</h3><div class="cart-meta">${p.label}</div><div class="qty"><button data-minus="${id}">−</button><strong>${q}</strong><button data-plus="${id}">+</button></div></div><button class="remove" data-remove="${id}">Quitar</button></div>`}).join(''):'<div class="empty">Tu pedido está vacío.<br>Agrega productos del catálogo.</div>';$('#cart-total').textContent=`${money(total)} MXN`;document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>change(b.dataset.minus,-1));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>change(b.dataset.plus,1));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{delete cart[b.dataset.remove];updateCart()})}
function openCart(){cartPanel.classList.add('open');overlay.classList.add('show');cartPanel.setAttribute('aria-hidden','false')}
function closeCart(){cartPanel.classList.remove('open');overlay.classList.remove('show');cartPanel.setAttribute('aria-hidden','true')}
function sendWhatsApp(){const entries=Object.entries(cart);if(!entries.length){toast('Agrega al menos un producto');return}let total=0;const lines=entries.map(([id,q])=>{const p=PRODUCTS.find(x=>x.id===id);if(p.price)total+=p.price*q;return `• ${p.name} x${q} — ${p.label}`});const text=`Hola, quiero hacer el siguiente pedido en TLAZOTLI:\n\n${lines.join('\n')}\n\nTotal estimado: ${money(total)} MXN\n\nNombre: `;window.open(`https://wa.me/528333074838?text=${encodeURIComponent(text)}`,'_blank')}
function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
search.addEventListener('input',render);category.addEventListener('change',render);sort.addEventListener('change',render);$('#cart-button').onclick=openCart;$('#close-cart').onclick=closeCart;overlay.onclick=closeCart;$('#clear-cart').onclick=()=>{cart={};updateCart()};$('#whatsapp-order').onclick=sendWhatsApp;initCategories();render();updateCart();